Removed trailing semi-colon - it was causing an error like the following one:
FRAGMENT glCompileShader "" FAILED
FRAGMENT Shader "" infolog:
ERROR: 0:38: ';' : syntax error syntax error